This is makeindex, version 2.15 [MiKTeX 2.9.6960 64-bit] (kpathsea + Thai support).
Scanning style file ./bachelor_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file bachelor_thesis.acn....done (102 entries accepted, 0 rejected).
Sorting entries....done (812 comparisons).
Generating output file bachelor_thesis.acr....done (70 lines written, 0 warnings).
Output written in bachelor_thesis.acr.
Transcript written in bachelor_thesis.alg.
